name: Build and upload wheel package

on:
  workflow_dispatch:

jobs:
    build-and-upload:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.x

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install wheel setuptools

            - name: Build wheel package
              run: |
                  python setup.py sdist bdist_wheel
            
            - name: Upload wheel package to s3
              run: |
                  pip install awscli
                  aws s3 cp dist/*.whl s3://${{ secrets.S3_BUCKET_NAME }}/ --recursive
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}